### ISSUE TITLE
sprintf typo

### ISSUE THREAD

**Issue by zqzneptune** [paul-shannon/cytofkit-extensions#1]
Hello, Paul,
It seems there is a typo on this line, which prevents implementing this function:

https://github.com/paul-shannon/cytofkit-extensions/blob/f7eded809d50ccd68b154d17b4c00f29f4e7fda0/R/CytofkitNormalization.R#L89

Should I make a quick PR to fix this?

Thanks!

Johnson

**Comment by paul-shannon** [comment]
good catch - thank you.
I have this convenience function defined previously in R. 
```
 printf <- function (...)  print(noquote(sprintf(...)))
```
shall we put it into the top of the file?

**Comment by zqzneptune** [comment]
I thinks so. I tested on my side, and it works now.

**Comment by paul-shannon** [comment]
@zqzneptune I just invited you to be a collaborator on this repo  - so you can make changes as we work together.
